version: "3.7"

services:

  airflow:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow
    restart: always
    volumes:
      - ./src:/usr/local/airflow/dags
      - ./data:/usr/local/airflow/data
    ports:
      - "8080:8080"